version: '3'
services: 
  db:
    container_name: bdjardineria
    image: mariadb
    environment:
      MARIADB_USER: jardinaria
      MARIADB_PASSWORD: pswjardineria
      MARIADB_DATABASE: jardineriagarden
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"