version: '3'
services:
  db:
    image: mariadb
    container_name: bdjardineria
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jardineriaDB
      MYSQL_USER: jardineria
      MYSQL_PASSWORD: pswjardineria
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"

