spring.application.name=jardineriagarden

# Hibernate settings
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update

#Datos de la conexión con MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3309/jardineriaDB
spring.datasource.username = jardineria
spring.datasource.password = pswjardineria