# spring.datasource.type=org.apache.tomcat.jdbc.pool.DataSource
spring.datasource.url=jdbc:mariadb://localhost:3307/jardineriaDB
spring.datasource.username = jardineria
spring.datasource.password = pswjardineria

spring.jpa.hibernate.ddl-auto=update
